"""
Django settings for openmu_web project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-9%km+8ulhq74dzxhjaranq48phi9osvhqeznzm6!0fh4wti0wc"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    "openmu.apps.OpenmuConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = "openmu_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.constant_template_variables",
            ],
        },
    },
]

WSGI_APPLICATION = "openmu_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# PostgreSQL multi scheme
# https://stackoverflow.com/a/51007441
# We use the connections to the OpenMU database and another internal database
# In the future, the internal database should be used for a bug tracker and news
DATABASES = {
    "default": {  # public
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "OPTIONS": {
            "service": "openmu_web_service",
            "passfile": ".openmu_web_pgpass",
        },
    },
    "config": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "OPTIONS": {
            "options": "-c search_path=config,public",
            "service": "openmu_service",
            "passfile": ".openmu_pgpass",
        },
    },
    "data": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "OPTIONS": {
            "options": "-c search_path=data,public",
            "service": "openmu_service",
            "passfile": ".openmu_pgpass",
        },
    },
    "friend": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "OPTIONS": {
            "options": "-c search_path=friend,public",
            "service": "openmu_service",
            "passfile": ".openmu_pgpass",
        },
    },
    "guild": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "OPTIONS": {
            "options": "-c search_path=guild,public",
            "service": "openmu_service",
            "passfile": ".openmu_pgpass",
        },
    },
}

DATABASE_ROUTERS = (
    "openmu.routers.DBConfigRouter",
    "openmu.routers.DBDataRouter",
    "openmu.routers.DBFriendRouter",
    "openmu.routers.DBGuildRouter",
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
